name: LineageOS-action-build

on:
    workflow_dispatch: 

jobs:
    build:
      runs-on: ubuntu-20.04
      steps:
      - name: Install the build packages
        run: |
          sudo apt update
          sudo apt -y install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python3 
      
      - name: Create the directories
        run: |
          mkdir -p ~/bin
          mkdir -p ~/android/lineage
      
      - name: Install the repo command
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          sudo cp ~/bin/repo /usr/bin/repo
          sudo chmod a+x ~/bin/repo
          sudo chmod a+x /usr/bin/repo

      - name: Configure git
        run: |
          git config --global user.email 666@test.com
          git config --global user.name test
      
      - name: Initialize the LineageOS source repository
        run: |
          cd ~/android/lineage
          repo init -u https://github.com/Halium/android -b halium-7.1 --depth=1 
          repo sync

      - name: Prepare the device-specific code
        run: |
          cd ~/android/lineage
          #git clone https://github.com/flydrz/android_device_oppo_PBEM00 -b dummy_lineage-17.1
          source build/envsetup.sh
          breakfast Z00A
      
      - name: Start the build
        run: |
          cd ~/android/lineage
          mka mkbootimg
          export USE_HOST_LEX=yes
          mka hybris-boot
          mka systemimage

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ~/android/lineage/$OUT/recovery.img
          name: lineageos-${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: lineageos 17.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
              ~/android/lineage/$OUT/lineage-*-UNOFFICIAL-dumpling.zip
          name: lineageos-${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: lineageos 17.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          


    

      


           
     








